// export const WS_ENDPOINT = 'ws://127.0.0.1:9944';
// export const WS_ENDPOINT = 'ws://127.0.0.1:9948';
// export const WS_ENDPOINT = 'ws://127.0.0.1:10048';
// export const WS_ENDPOINT = 'ws://127.0.0.1:10044';
// export const WS_ENDPOINT = 'wss://ws-rc.unique.network';
// export const WS_ENDPOINT = 'wss://us-ws-westend.unique.network';
// export const WS_ENDPOINT = 'wss://us-ws-eastend.unique.network';
// export const WS_ENDPOINT = 'wss://us-ws-opal.unique.network';
export const WS_ENDPOINT = 'wss://ws-rc-tests2.unique.network';
