# ===== Integration Tests ======


FROM ubuntu:18.04
LABEL maintainer="UniqueNetwork.io"

RUN apt-get -y update; apt-get -y upgrade; apt-get -y install curl


RUN mkdir nft_parachain
WORKDIR /nft_parachain

COPY . .

RUN apt-get -y update && \
      apt-get -y upgrade && \
      apt-get -y install curl && \
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
      export NVM_DIR="$HOME/.nvm" && \
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
      nvm install v15.0.1 && \
      nvm use v15.0.1 && \
      npm install --save @polkadot/api && \ 
      npm install --save-dev mochawesome

CMD export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd tests && \
    npm install --global yarn && 
    yarn add mochawesome && \
    yarn install && \
    yarn test --reporter mochawesome
   # yarn test
