// FIXME REGENERATE THIS!!!
// Template adopted from https://github.com/paritytech/substrate/blob/master/.maintain/frame-weight-template.hbs

//! Autogenerated weights for pallet_foreign_assets
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-28, STEPS: `50`, REPEAT: `80`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `hearthstone`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/production/unique-collator
// benchmark
// pallet
// --pallet
// pallet-foreign-assets
// --wasm-execution
// compiled
// --extrinsic
// *
// --template=.maintain/frame-weight-template.hbs
// --steps=50
// --repeat=80
// --heap-pages=4096
// --output=./pallets/foreign-assets/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_foreign_assets.
pub trait WeightInfo {
	fn force_register_foreign_asset() -> Weight;
	fn force_reset_foreign_asset_location() -> Weight;
	fn force_set_foreign_asset_reserve_override() -> Weight;
	fn force_set_foreign_asset_suspension() -> Weight;
	fn add_oracle_member() -> Weight;
	fn remove_oracle_member() -> Weight;
	fn force_set_foreign_asset_conversion_coefficient() -> Weight;
	fn update_currency_exchange_url() -> Weight;
	fn set_exchange_rate_update_interval() -> Weight;
}

/// Weights for pallet_foreign_assets using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ForeignAssets::ForeignAssetToCollection` (r:1 w:1)
	/// Proof: `ForeignAssets::ForeignAssetToCollection` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `Common::CreatedCollectionCount` (r:1 w:1)
	/// Proof: `Common::CreatedCollectionCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Common::DestroyedCollectionCount` (r:1 w:0)
	/// Proof: `Common::DestroyedCollectionCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::CollectionToForeignAsset` (r:0 w:1)
	/// Proof: `ForeignAssets::CollectionToForeignAsset` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `Common::AdminAmount` (r:0 w:1)
	/// Proof: `Common::AdminAmount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Common::CollectionPropertyPermissions` (r:0 w:1)
	/// Proof: `Common::CollectionPropertyPermissions` (`max_values`: None, `max_size`: Some(16726), added: 19201, mode: `MaxEncodedLen`)
	/// Storage: `Common::CollectionProperties` (r:0 w:1)
	/// Proof: `Common::CollectionProperties` (`max_values`: None, `max_size`: Some(40990), added: 43465, mode: `MaxEncodedLen`)
	/// Storage: `Common::CollectionById` (r:0 w:1)
	/// Proof: `Common::CollectionById` (`max_values`: None, `max_size`: Some(860), added: 3335, mode: `MaxEncodedLen`)
	fn force_register_foreign_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `4087`
		// Minimum execution time: 16_341_000 picoseconds.
		Weight::from_parts(16_761_000, 4087)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ForeignAssets::ForeignAssetToCollection` (r:1 w:2)
	/// Proof: `ForeignAssets::ForeignAssetToCollection` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::CollectionToForeignAsset` (r:0 w:1)
	/// Proof: `ForeignAssets::CollectionToForeignAsset` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	fn force_reset_foreign_asset_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92`
		//  Estimated: `4087`
		// Minimum execution time: 9_979_000 picoseconds.
		Weight::from_parts(10_269_000, 4087)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ForeignAssets::ForeignAssetReserveOverride` (r:0 w:1)
	/// Proof: `ForeignAssets::ForeignAssetReserveOverride` (`max_values`: None, `max_size`: Some(1220), added: 3695, mode: `MaxEncodedLen`)
	fn force_set_foreign_asset_reserve_override() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_067_000 picoseconds.
		Weight::from_parts(4_268_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::SuspendedForeignAsset` (r:0 w:1)
	/// Proof: `ForeignAssets::SuspendedForeignAsset` (`max_values`: None, `max_size`: Some(619), added: 3094, mode: `MaxEncodedLen`)
	fn force_set_foreign_asset_suspension() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_637_000 picoseconds.
		Weight::from_parts(3_777_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::OracleMembers` (r:1 w:1)
	/// Proof: `ForeignAssets::OracleMembers` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
	fn add_oracle_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3086`
		// Minimum execution time: 2_895_000 picoseconds.
		Weight::from_parts(3_066_000, 3086)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::OracleMembers` (r:1 w:1)
	/// Proof: `ForeignAssets::OracleMembers` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
	fn remove_oracle_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3086`
		// Minimum execution time: 2_865_000 picoseconds.
		Weight::from_parts(3_036_000, 3086)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::ForeignAssetConversionCoefficient` (r:1 w:1)
	/// Proof: `ForeignAssets::ForeignAssetConversionCoefficient` (`max_values`: None, `max_size`: Some(634), added: 3109, mode: `MaxEncodedLen`)
	fn force_set_foreign_asset_conversion_coefficient() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `4099`
		// Minimum execution time: 6_202_000 picoseconds.
		Weight::from_parts(6_473_000, 4099)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::CurrencyExchangeUrl` (r:0 w:1)
	/// Proof: `ForeignAssets::CurrencyExchangeUrl` (`max_values`: Some(1), `max_size`: Some(202), added: 697, mode: `MaxEncodedLen`)
	fn update_currency_exchange_url() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_503_000 picoseconds.
		Weight::from_parts(1_643_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::ExchangeRateUpdateInterval` (r:0 w:1)
	/// Proof: `ForeignAssets::ExchangeRateUpdateInterval` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_exchange_rate_update_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_193_000 picoseconds.
		Weight::from_parts(1_292_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `ForeignAssets::ForeignAssetToCollection` (r:1 w:1)
	/// Proof: `ForeignAssets::ForeignAssetToCollection` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `Common::CreatedCollectionCount` (r:1 w:1)
	/// Proof: `Common::CreatedCollectionCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Common::DestroyedCollectionCount` (r:1 w:0)
	/// Proof: `Common::DestroyedCollectionCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::CollectionToForeignAsset` (r:0 w:1)
	/// Proof: `ForeignAssets::CollectionToForeignAsset` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `Common::AdminAmount` (r:0 w:1)
	/// Proof: `Common::AdminAmount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Common::CollectionPropertyPermissions` (r:0 w:1)
	/// Proof: `Common::CollectionPropertyPermissions` (`max_values`: None, `max_size`: Some(16726), added: 19201, mode: `MaxEncodedLen`)
	/// Storage: `Common::CollectionProperties` (r:0 w:1)
	/// Proof: `Common::CollectionProperties` (`max_values`: None, `max_size`: Some(40990), added: 43465, mode: `MaxEncodedLen`)
	/// Storage: `Common::CollectionById` (r:0 w:1)
	/// Proof: `Common::CollectionById` (`max_values`: None, `max_size`: Some(860), added: 3335, mode: `MaxEncodedLen`)
	fn force_register_foreign_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `4087`
		// Minimum execution time: 16_341_000 picoseconds.
		Weight::from_parts(16_761_000, 4087)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ForeignAssets::ForeignAssetToCollection` (r:1 w:2)
	/// Proof: `ForeignAssets::ForeignAssetToCollection` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::CollectionToForeignAsset` (r:0 w:1)
	/// Proof: `ForeignAssets::CollectionToForeignAsset` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	fn force_reset_foreign_asset_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92`
		//  Estimated: `4087`
		// Minimum execution time: 9_979_000 picoseconds.
		Weight::from_parts(10_269_000, 4087)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ForeignAssets::ForeignAssetReserveOverride` (r:0 w:1)
	/// Proof: `ForeignAssets::ForeignAssetReserveOverride` (`max_values`: None, `max_size`: Some(1220), added: 3695, mode: `MaxEncodedLen`)
	fn force_set_foreign_asset_reserve_override() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_067_000 picoseconds.
		Weight::from_parts(4_268_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::SuspendedForeignAsset` (r:0 w:1)
	/// Proof: `ForeignAssets::SuspendedForeignAsset` (`max_values`: None, `max_size`: Some(619), added: 3094, mode: `MaxEncodedLen`)
	fn force_set_foreign_asset_suspension() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_637_000 picoseconds.
		Weight::from_parts(3_777_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::OracleMembers` (r:1 w:1)
	/// Proof: `ForeignAssets::OracleMembers` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
	fn add_oracle_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3086`
		// Minimum execution time: 2_895_000 picoseconds.
		Weight::from_parts(3_066_000, 3086)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::OracleMembers` (r:1 w:1)
	/// Proof: `ForeignAssets::OracleMembers` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
	fn remove_oracle_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3086`
		// Minimum execution time: 2_865_000 picoseconds.
		Weight::from_parts(3_036_000, 3086)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::ForeignAssetConversionCoefficient` (r:1 w:1)
	/// Proof: `ForeignAssets::ForeignAssetConversionCoefficient` (`max_values`: None, `max_size`: Some(634), added: 3109, mode: `MaxEncodedLen`)
	fn force_set_foreign_asset_conversion_coefficient() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `4099`
		// Minimum execution time: 6_202_000 picoseconds.
		Weight::from_parts(6_473_000, 4099)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::CurrencyExchangeUrl` (r:0 w:1)
	/// Proof: `ForeignAssets::CurrencyExchangeUrl` (`max_values`: Some(1), `max_size`: Some(202), added: 697, mode: `MaxEncodedLen`)
	fn update_currency_exchange_url() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_503_000 picoseconds.
		Weight::from_parts(1_643_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ForeignAssets::ExchangeRateUpdateInterval` (r:0 w:1)
	/// Proof: `ForeignAssets::ExchangeRateUpdateInterval` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_exchange_rate_update_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_193_000 picoseconds.
		Weight::from_parts(1_292_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}

