# ===== Integration Tests ======


FROM ubuntu:20.04
LABEL maintainer="UniqueNetwork.io"

RUN apt -y update; apt -y upgrade; apt -y install curl


RUN mkdir nft_parachain
WORKDIR /nft_parachain

RUN apt-get -y update && \
      apt-get -y upgrade && \
      apt-get -y install curl jq && \
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
      export NVM_DIR="$HOME/.nvm" && \
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
      nvm install v16.2.0 && \
      nvm alias default v16.2.0 && \
      nvm use default

ENV YARN_CACHE_FOLDER ~/.yarn

COPY package.json yarn.lock ./

RUN export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    npm install --global yarn && \
    yarn add mochawesome && \
    yarn --pure-lockfile

COPY . .

CMD export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    ./scripts/wait_for_first_block.sh && \
    NOW=$(date +%s) && yarn test --reporter mochawesome --reporter-options reportFilename=test-${NOW}
