# ===== Rust builder =====
FROM phusion/baseimage:focal-1.1.0 as rust-builder
LABEL maintainer="Unique.Network"

ARG RUST_TOOLCHAIN=nightly-2022-05-11
ARG UNIQUE_BRANCH=develop

ENV RUST_TOOLCHAIN $RUST_TOOLCHAIN
ENV UNIQUE_BRANCH $UNIQUE_BRANCH

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

RUN apt-get update && \
    apt-get dist-upgrade -y -o Dpkg::Options::="--force-confold" && \
    apt-get install -y cmake pkg-config libssl-dev git clang

RUN rustup toolchain uninstall $(rustup toolchain list) && \
    rustup toolchain install $RUST_TOOLCHAIN && \
    rustup default $RUST_TOOLCHAIN && \
    rustup target list --installed && \
    rustup show
RUN rustup target add wasm32-unknown-unknown --toolchain $RUST_TOOLCHAIN

RUN cargo install cargo-chef

RUN mkdir unique_parachain
WORKDIR /unique_parachain

# ===== Chef =====
FROM rust-builder as chef

COPY . .
RUN cargo chef prepare --recipe-path recipe.json

# ===== BUILD ======
FROM rust-builder as builder

RUN mkdir unique_parachain
WORKDIR /unique_parachain

COPY --from=chef /unique_parachain/recipe.json recipe.json
RUN cargo chef cook "--release" --recipe-path recipe.json

COPY . .
ARG RUNTIME=quartz
RUN cargo build --release "--features=$RUNTIME-runtime"

# ===== BUILD POLKADOT =====
FROM rust-builder as builder-polkadot

RUN mkdir unique_parachain
WORKDIR /unique_parachain

ARG POLKA_VERSION=release-v0.9.24
RUN git clone -b $POLKA_VERSION --depth 1 https://github.com/paritytech/polkadot.git && \
    cd polkadot && \
    cargo build --release

# ===== BUILD CHAINQL =====
FROM rust-builder as builder-chainql

RUN mkdir chainql
WORKDIR /chainql

RUN git clone --depth 1 https://github.com/CertainLach/chainql.git . && \
    cargo build --release

# ===== RUN ======

FROM phusion/baseimage:focal-1.1.0

RUN apt-get -y update && \
      apt-get -y upgrade && \
      apt-get -y install curl git && \
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
      export NVM_DIR="$HOME/.nvm" && \
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
      nvm install v15.5.0 && \
      nvm use v15.5.0

RUN git clone https://github.com/uniquenetwork/polkadot-launch -b feature/parachain-forking

RUN export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    npm install --global yarn && \
    yarn

COPY --from=builder /unique_parachain/target/release/unique-collator /unique-chain/target/release/
COPY --from=builder-polkadot /unique_parachain/polkadot/target/release/polkadot /polkadot/target/release/
COPY --from=builder-chainql /chainql/target/release/chainql /chainql/target/release/

ARG FORK_FROM=wss://eu-ws-quartz.unique.network:443
ENV FORK_FROM=$FORK_FROM
CMD export NVM_DIR="$HOME/.nvm" PATH="$PATH:/chainql/target/release" FORK_FROM && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    yarn start launch-config.json
