/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Approval = ContractEventLog<{
  owner: string;
  spender: string;
  value: string;
  0: string;
  1: string;
  2: string;
}>;
export type Transfer = ContractEventLog<{
  from: string;
  to: string;
  value: string;
  0: string;
  1: string;
  2: string;
}>;

export interface FungibleAbi extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): FungibleAbi;
  clone(): FungibleAbi;
  methods: {
    addCollectionAdmin(newAdmin: string): NonPayableTransactionObject<void>;

    addCollectionAdminCross(
      newAdmin: [string, number | string | BN]
    ): NonPayableTransactionObject<void>;

    addToCollectionAllowList(user: string): NonPayableTransactionObject<void>;

    addToCollectionAllowListCross(
      user: [string, number | string | BN]
    ): NonPayableTransactionObject<void>;

    allowance(
      owner: string,
      spender: string
    ): NonPayableTransactionObject<string>;

    allowed(user: string): NonPayableTransactionObject<boolean>;

    approve(
      spender: string,
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    approveCross(
      spender: [string, number | string | BN],
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    balanceOf(owner: string): NonPayableTransactionObject<string>;

    burnFrom(
      from: string,
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    burnFromCross(
      from: [string, number | string | BN],
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    changeCollectionOwner(newOwner: string): NonPayableTransactionObject<void>;

    collectionAdmins(): NonPayableTransactionObject<[string, string][]>;

    collectionOwner(): NonPayableTransactionObject<[string, string]>;

    collectionProperties(
      keys: string[]
    ): NonPayableTransactionObject<[string, string][]>;

    collectionProperty(key: string): NonPayableTransactionObject<string>;

    collectionSponsor(): NonPayableTransactionObject<[string, string]>;

    confirmCollectionSponsorship(): NonPayableTransactionObject<void>;

    contractAddress(): NonPayableTransactionObject<string>;

    decimals(): NonPayableTransactionObject<string>;

    deleteCollectionProperties(
      keys: string[]
    ): NonPayableTransactionObject<void>;

    deleteCollectionProperty(key: string): NonPayableTransactionObject<void>;

    hasCollectionPendingSponsor(): NonPayableTransactionObject<boolean>;

    isOwnerOrAdmin(user: string): NonPayableTransactionObject<boolean>;

    isOwnerOrAdminCross(
      user: [string, number | string | BN]
    ): NonPayableTransactionObject<boolean>;

    mint(
      to: string,
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    mintBulk(
      amounts: [string, number | string | BN][]
    ): NonPayableTransactionObject<boolean>;

    name(): NonPayableTransactionObject<string>;

    removeCollectionAdmin(admin: string): NonPayableTransactionObject<void>;

    removeCollectionAdminCross(
      admin: [string, number | string | BN]
    ): NonPayableTransactionObject<void>;

    removeCollectionSponsor(): NonPayableTransactionObject<void>;

    removeFromCollectionAllowList(
      user: string
    ): NonPayableTransactionObject<void>;

    removeFromCollectionAllowListCross(
      user: [string, number | string | BN]
    ): NonPayableTransactionObject<void>;

    setCollectionAccess(
      mode: number | string | BN
    ): NonPayableTransactionObject<void>;

    "setCollectionLimit(string,uint32)"(
      limit: string,
      value: number | string | BN
    ): NonPayableTransactionObject<void>;

    "setCollectionLimit(string,bool)"(
      limit: string,
      value: boolean
    ): NonPayableTransactionObject<void>;

    setCollectionMintMode(mode: boolean): NonPayableTransactionObject<void>;

    "setCollectionNesting(bool)"(
      enable: boolean
    ): NonPayableTransactionObject<void>;

    "setCollectionNesting(bool,address[])"(
      enable: boolean,
      collections: string[]
    ): NonPayableTransactionObject<void>;

    setCollectionProperties(
      properties: [string, string | number[]][]
    ): NonPayableTransactionObject<void>;

    setCollectionProperty(
      key: string,
      value: string | number[]
    ): NonPayableTransactionObject<void>;

    setCollectionSponsor(sponsor: string): NonPayableTransactionObject<void>;

    setCollectionSponsorCross(
      sponsor: [string, number | string | BN]
    ): NonPayableTransactionObject<void>;

    setOwnerCross(
      newOwner: [string, number | string | BN]
    ): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceID: string | number[]
    ): NonPayableTransactionObject<boolean>;

    symbol(): NonPayableTransactionObject<string>;

    totalSupply(): NonPayableTransactionObject<string>;

    transfer(
      to: string,
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    transferFrom(
      from: string,
      to: string,
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    transferFromCross(
      from: [string, number | string | BN],
      to: [string, number | string | BN],
      amount: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    uniqueCollectionType(): NonPayableTransactionObject<string>;
  };
  events: {
    Approval(cb?: Callback<Approval>): EventEmitter;
    Approval(options?: EventOptions, cb?: Callback<Approval>): EventEmitter;

    Transfer(cb?: Callback<Transfer>): EventEmitter;
    Transfer(options?: EventOptions, cb?: Callback<Transfer>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Approval", cb: Callback<Approval>): void;
  once(event: "Approval", options: EventOptions, cb: Callback<Approval>): void;

  once(event: "Transfer", cb: Callback<Transfer>): void;
  once(event: "Transfer", options: EventOptions, cb: Callback<Transfer>): void;
}
