# ===== BUILD POLKADOT =====
FROM "uniquenetwork/services:base-nightly-1.67.0" AS builder

WORKDIR /workdir

COPY . unique-chain/

ARG FEATURES

RUN cd unique-chain && \
    echo "Using runtime features ${FEATURES}" && \
    CARGO_INCREMENTAL=0 WASM_BUILD_TYPE=integration-tests cargo build --profile integration-tests --features=fast-inflation,"${FEATURES}" --locked && \
    mv ./target/integration-tests/unique-collator /workdir/unique-chain/ && \
    cd target/integration-tests/wbuild && find . -name "*.wasm" -exec sh -c 'mkdir -p "../../../wasm/$(dirname {})"; cp {} "../../../wasm/{}"' \;

# ===== BIN ======

FROM ubuntu:24.04 
LABEL maintainer="Unique.Network"

COPY --from=builder /workdir/unique-chain/unique-collator /bin/unique-collator
COPY --from=builder /workdir/unique-chain/wasm /wasm
ENTRYPOINT ["/bin/unique-collator"]
