FROM uniquenetwork/services:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"

ARG NETWORK

RUN mkdir /dev_chain
COPY . /dev_chain

WORKDIR /dev_chain

CMD cargo test --features=limit-testing,tests --workspace
