# ===== Rust builder =====
FROM phusion/baseimage:focal-1.1.0 as rust-builder
LABEL maintainer="Unique.Network"

ARG RUST_TOOLCHAIN=nightly-2022-05-11
ARG POLKA_VERSION=release-v0.9.24


ENV RUST_TOOLCHAIN $RUST_TOOLCHAIN
ENV POLKA_VERSION $POLKA_VERSION

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

RUN apt-get update && \
    apt-get dist-upgrade -y -o Dpkg::Options::="--force-confold" && \
    apt-get install -y cmake pkg-config libssl-dev git clang

RUN rustup toolchain uninstall $(rustup toolchain list) && \
    rustup toolchain install $RUST_TOOLCHAIN && \
    rustup default $RUST_TOOLCHAIN && \
    rustup target list --installed && \
    rustup show
RUN rustup target add wasm32-unknown-unknown --toolchain $RUST_TOOLCHAIN

####works inside repo folder###


# ===== BUILD ======
FROM rust-builder as builder-unique

RUN mkdir unique_parachain
WORKDIR /unique_parachain

ARG FEATURE=' '

COPY . .
RUN cargo build $FEATURE --release
   # && \
   # cargo test

# ===== BUILD POLKADOT =====
FROM rust-builder as builder-polkadot

RUN mkdir unique_parachain
WORKDIR /unique_parachain

RUN git clone -b $POLKA_VERSION --depth 1 https://github.com/paritytech/polkadot.git && \
    cd polkadot && \
    git tag -n && \
	cargo build --release

# ===== RUN ======

FROM phusion/baseimage:focal-1.1.0

RUN apt-get -y update && \
      apt-get -y upgrade && \
      apt-get -y install curl git && \
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
      export NVM_DIR="$HOME/.nvm" && \
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
      nvm install v15.5.0 && \
      nvm use v15.5.0

RUN git clone https://github.com/UniqueNetwork/polkadot-launch.git && \
    cd /polkadot-launch && \
    git checkout feature/runtime-upgrade-testing

RUN export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    npm install --global yarn && \
    yarn

COPY --from=builder-unique /unique_parachain/target/release/unique-collator /unique-chain/target/release/
COPY --from=builder-polkadot /unique_parachain/polkadot/target/release/polkadot /polkadot/target/release/

COPY ["./launch-config.json", "/polkadot-launch/launch-config.json"]


EXPOSE 9844
EXPOSE 9944
EXPOSE 9933
EXPOSE 9833
EXPOSE 40333
EXPOSE 30333

CMD export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    yarn start launch-config.json
