# ===== Rust builder =====
FROM ubuntu:20.04 as rust-builder
LABEL maintainer="Unique.Network"

ARG RUST_TOOLCHAIN=

ENV RUST_TOOLCHAIN $RUST_TOOLCHAIN
ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

RUN rustup toolchain uninstall $(rustup toolchain list) && \
    rustup toolchain install $RUST_TOOLCHAIN && \
    rustup default $RUST_TOOLCHAIN && \
    rustup target list --installed && \
    rustup show
RUN rustup target add wasm32-unknown-unknown --toolchain $RUST_TOOLCHAIN

RUN mkdir /unique_parachain
WORKDIR /unique_parachain


# ===== BUILD ======
FROM rust-builder as builder-unique

ARG PROFILE=release
ARG FEATURE=
ARG REPO_URL=
ARG BRANCH=


WORKDIR /unique_parachain

RUN git clone $REPO_URL -b $BRANCH . && \
    cargo build --features=$FEATURE --$PROFILE

# ===== BUILD POLKADOT =====
FROM rust-builder as builder-polkadot

ARG POLKADOT_BUILD_BRANCH=
ENV POLKADOT_BUILD_BRANCH $POLKADOT_BUILD_BRANCH


WORKDIR /unique_parachain

RUN git clone -b $POLKADOT_BUILD_BRANCH --depth 1 https://github.com/paritytech/polkadot.git && \
    cd polkadot && \
    cargo build --release

# ===== BUILD ACALA =====
FROM rust-builder as builder-acala

ARG ACALA_BUILD_BRANCH=
ENV ACALA_BUILD_BRANCH $ACALA_BUILD_BRANCH


WORKDIR /unique_parachain

RUN git clone -b $ACALA_BUILD_BRANCH --depth 1 https://github.com/AcalaNetwork/Acala.git && \
    cd Acala && \
    make init && \
    cargo build --release

# ===== BUILD MOONBEAM =====
FROM rust-builder as builder-moonbeam

ARG MOONBEAM_BUILD_BRANCH=
ENV MOONBEAM_BUILD_BRANCH $MOONBEAM_BUILD_BRANCH


WORKDIR /unique_parachain

RUN git clone -b $MOONBEAM_BUILD_BRANCH --depth 1 https://github.com/PureStake/moonbeam.git && \
    cd moonbeam && \
    cargo build --release

# ===== BUILD CUMULUS =====
FROM rust-builder as builder-cumulus

ARG CUMULUS_BUILD_BRANCH=
ENV CUMULUS_BUILD_BRANCH $CUMULUS_BUILD_BRANCH


WORKDIR /unique_parachain

RUN git clone -b $CUMULUS_BUILD_BRANCH --depth 1 https://github.com/paritytech/cumulus.git && \
    cd cumulus && \
    cargo build --release

# ===== RUN ======

FROM ubuntu:20.04

RUN apt-get -y update && \
      apt-get -y install curl git && \
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
      export NVM_DIR="$HOME/.nvm" && \
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
      nvm install v16.16.0 && \
      nvm use v16.16.0

RUN git clone https://github.com/uniquenetwork/polkadot-launch -b feature/runtime-upgrade-testing

RUN export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    npm install --global yarn && \
    yarn install

COPY --from=builder-unique /unique_parachain/target/release/unique-collator /unique-chain/target/release/
COPY --from=builder-polkadot /unique_parachain/polkadot/target/release/polkadot /polkadot/target/release/
COPY --from=builder-acala /unique_parachain/Acala/target/production/acala /acala/target/release/
COPY --from=builder-moonbeam /unique_parachain/moonbeam/target/release/moonbeam /moonbeam/target/release/
COPY --from=builder-cumulus /unique_parachain/cumulus/target/release/polkadot-parachain /cumulus/target/release/cumulus

CMD export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    yarn start launch-config.json
