# ===== Rust builder =====
FROM uniquenetwork/services:latest as rust-builder
ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC

RUN rustup toolchain uninstall $(rustup toolchain list) && \
    rustup toolchain install {{ RUST_TOOLCHAIN }} && \
    rustup default {{ RUST_TOOLCHAIN }} && \
    rustup target list --installed && \
    rustup show
RUN rustup target add wasm32-unknown-unknown --toolchain {{ RUST_TOOLCHAIN }}

RUN mkdir /unique_parachain
WORKDIR /unique_parachain

# ===== BUILD ======
FROM rust-builder as builder-unique

ARG PROFILE=release

WORKDIR /unique_parachain

COPY ./xcm-config/launch-config-xcm-{{ NETWORK }}.json ./launch-config-xcm-{{ NETWORK }}.json
COPY ./xcm-config/5validators.jsonnet ./5validators.jsonnet

RUN git clone -b {{ BRANCH }} https://github.com/UniqueNetwork/unique-chain.git && \
    cd unique-chain && \
    cargo build --features={{ NETWORK }}-runtime --$PROFILE

# ===== RUN ======

FROM ubuntu:22.04

RUN apt-get -y update && \
      apt-get -y install curl git && \
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
      export NVM_DIR="$HOME/.nvm" && \
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
      nvm install v16.16.0 && \
      nvm use v16.16.0

RUN git clone https://github.com/uniquenetwork/polkadot-launch -b {{ POLKADOT_LAUNCH_BRANCH }}

RUN export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    npm install --global yarn && \
    yarn install

COPY --from=builder-unique /unique_parachain/launch-config-xcm-{{ NETWORK }}.json /polkadot-launch/
COPY --from=builder-unique /unique_parachain/5validators.jsonnet /polkadot-launch/5validators.jsonnet

COPY --from=builder-unique /unique_parachain/unique-chain/target/release/unique-collator /unique-chain/target/release/

COPY --from=uniquenetwork/builder-polkadot:{{ POLKADOT_BUILD_BRANCH }} /unique_parachain/polkadot/target/release/polkadot /polkadot/target/release/
COPY --from=uniquenetwork/builder-moonbeam:{{ MOONBEAM_BUILD_BRANCH }} /unique_parachain/moonbeam/target/release/moonbeam /moonbeam/target/release/
COPY --from=uniquenetwork/builder-cumulus:{{ CUMULUS_BUILD_BRANCH }} /unique_parachain/cumulus/target/release/polkadot-parachain /cumulus/target/release/cumulus
COPY --from=uniquenetwork/builder-acala:{{ ACALA_BUILD_BRANCH }} /unique_parachain/acala/target/production/acala /acala/target/release/
COPY --from=uniquenetwork/builder-astar:{{ ASTAR_BUILD_BRANCH }} /unique_parachain/astar/target/release/astar /astar/target/release/
COPY --from=uniquenetwork/builder-chainql:latest /chainql/target/release/chainql /chainql/target/release/

EXPOSE 9844
EXPOSE 9933
EXPOSE 9944
EXPOSE 9946
EXPOSE 9947
EXPOSE 9948
EXPOSE 9949

CMD export NVM_DIR="$HOME/.nvm" PATH="$PATH:/chainql/target/release" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    cd /polkadot-launch && \
    yarn start launch-config-xcm-{{ NETWORK }}.json
