ARG POLKADOT_BUILD_BRANCH
FROM uniquenetwork/builder-polkadot:${POLKADOT_BUILD_BRANCH} as polkadot

# ===== RUN ======
FROM ubuntu:20.04

COPY --from=polkadot /unique_parachain/polkadot/target/release/polkadot /polkadot/target/release/

