# ===== Rust builder =====
FROM uniquenetwork/services:latest as rust-builder

ENV RUST_TOOLCHAIN {{ RUST_TOOLCHAIN }}
ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC

RUN rustup toolchain uninstall $(rustup toolchain list) && \
    rustup toolchain install {{ RUST_TOOLCHAIN }} && \
    rustup default {{ RUST_TOOLCHAIN }} && \
    rustup target list --installed && \
    rustup show
RUN rustup target add wasm32-unknown-unknown --toolchain {{ RUST_TOOLCHAIN }}

RUN mkdir /unique_parachain
WORKDIR /unique_parachain


# ===== BUILD ======
FROM rust-builder as builder-unique

ARG PROFILE=release
ARG GIT_PRIVATE_CREDENTIALS

COPY . /unique_parachain
WORKDIR /unique_parachain

RUN git config --global url."https://$GIT_PRIVATE_CREDENTIALS@github.com".insteadOf ssh://git@github.com

RUN echo "Requested features: {{ NETWORK }}-runtime\n" && \
    echo "Fork from: {{ REPLICA_FROM }}\n" && \
    cargo build --features=try-runtime,{{ NETWORK }}-runtime --release

CMD cargo run --release --features {{ NETWORK }}-runtime,try-runtime -- try-runtime --runtime target/release/wbuild/{{ WASM_NAME }}-runtime/{{ WASM_NAME }}_runtime.compact.compressed.wasm -lruntime=debug -ltry-runtime::cli=debug on-runtime-upgrade --checks live --uri {{ REPLICA_FROM }}
