FROM uniquenetwork/services:base-nightly-1.67.0

ARG NETWORK

COPY . /workdir
WORKDIR /workdir

RUN cargo build --profile integration-tests --features=${NETWORK}-runtime,fast-inflation

CMD WASM_BUILD_TYPE=integration-tests && cargo run --profile integration-tests --features=${NETWORK}-runtime,fast-inflation -- --dev -linfo --rpc-cors=all --unsafe-rpc-external
