# ===== Rust builder =====
FROM ubuntu:22.04 as rust-builder
LABEL maintainer="Unique.Network"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

RUN rustup toolchain install {{ RUST_TOOLCHAIN }} && \
    rustup target add wasm32-unknown-unknown --toolchain {{ RUST_TOOLCHAIN }} && \
    rustup default {{ RUST_TOOLCHAIN }} && \
    rustup component add --toolchain {{ RUST_TOOLCHAIN }} rust-src && \
    rustup target list --installed && \
    rustup show

RUN mkdir /unique_parachain
WORKDIR /unique_parachain

# ===== BUILD POLKADOT =====
FROM rust-builder as builder-polkadot-bin

WORKDIR /unique_parachain

RUN git clone -b {{ POLKADOT_BUILD_BRANCH }} --depth 1 https://github.com/paritytech/polkadot.git

RUN --mount=type=cache,target=/cargo-home/registry \
    --mount=type=cache,target=/cargo-home/git \
    --mount=type=cache,target=/unique_parachain/polkadot/target \
    cd polkadot && \
    CARGO_INCREMENTAL=0 cargo build --release --locked && \
    mv ./target/release/polkadot /unique_parachain/polkadot/

# ===== BIN ======

FROM ubuntu:22.04 as builder-polkadot

COPY --from=builder-polkadot-bin /unique_parachain/polkadot/polkadot /bin/polkadot
ENTRYPOINT ["/bin/polkadot"]
