FROM uniquenetwork/services:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"

ARG RUST_TOOLCHAIN
ARG NETWORK

RUN rustup toolchain uninstall $(rustup toolchain list) && \
    rustup toolchain install $RUST_TOOLCHAIN && \
    rustup default $RUST_TOOLCHAIN && \
    rustup target add wasm32-unknown-unknown --toolchain $RUST_TOOLCHAIN

RUN mkdir /dev_chain
COPY . /dev_chain

WORKDIR /dev_chain

ARG GIT_PRIVATE_CREDENTIALS

#RUN git config --global url."https://$GIT_PRIVATE_CREDENTIALS@github.com".insteadOf ssh://git@github.com

CMD cargo test --features=limit-testing,tests --workspace
