# ===== BUILD POLKADOT =====
FROM uniquenetwork/services:base-stable-1.77.0 as builder

WORKDIR /workdir

ARG UNIQUE_VERSION
RUN git clone -b "$UNIQUE_VERSION" --depth 1 https://github.com/uniquenetwork/unique-chain.git

ARG FEATURES
RUN --mount=type=cache,target=/cargo-home/registry \
    --mount=type=cache,target=/cargo-home/git \
    --mount=type=cache,target=/workdir/unique-chain/target \
    cd unique-chain && \
    CARGO_INCREMENTAL=0 cargo build --release --features="${FEATURES}" --locked && \
    mv ./target/release/unique-collator /workdir/unique-chain/

# ===== BIN ======

FROM ubuntu:24.04 as builder-polkadot

COPY --from=builder-polkadot-bin /workdir/unique-chain/unique-collator /bin/unique-collator
ENTRYPOINT ["/bin/unique-collator"]
