# ===== Rust builder =====
FROM ubuntu:22.04 as rust-builder
LABEL maintainer="Unique.Network"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

RUN rustup toolchain install {{ RUST_TOOLCHAIN }} && \
    rustup target add wasm32-unknown-unknown --toolchain {{ RUST_TOOLCHAIN }} && \
    rustup default {{ RUST_TOOLCHAIN }} && \
    rustup target list --installed && \
    rustup show

RUN mkdir /unique_parachain
WORKDIR /unique_parachain

# ===== BUILD ACALA =====
FROM rust-builder as builder-polkadex-bin

WORKDIR /unique_parachain

RUN git clone --depth 1 -b {{ POLKADEX_BUILD_BRANCH }} https://github.com/Polkadex-Substrate/parachain.git

RUN --mount=type=cache,target=/cargo-home/registry \
    --mount=type=cache,target=/cargo-home/git \
    --mount=type=cache,target=/unique_parachain/parachain/target \
    cd parachain && \
    CARGO_INCREMENTAL=0 cargo build --release --locked && \
    mv ./target/release/parachain-polkadex-node /unique_parachain/Polkadex/polkadex

# ===== BIN ======

FROM ubuntu:22.04 as builder-polkadex

COPY --from=builder-polkadex-bin /unique_parachain/Polkadex/polkadex /bin/polkadex
ENTRYPOINT ["/bin/polkadex"]
