# ===== BUILD POLKADOT =====
FROM "uniquenetwork/services:base-nightly-1.67.0" AS builder

WORKDIR /workdir

ARG CODE_VERSION
ARG CODE_HASH
ARG FEATURES

RUN git clone -b "${CODE_VERSION}" https://github.com/uniquenetwork/unique-chain.git && \
    cd unique-chain && git switch "${CODE_HASH}" --detach && \
    CARGO_INCREMENTAL=0 cargo build --release --features="${FEATURES}" --locked && \
    mv ./target/release/unique-collator /workdir/unique-chain/ && \
    cd target/release/wbuild && find . -name "*.wasm" -exec sh -c 'mkdir -p "../../../wasm/$(dirname {})"; cp {} "../../../wasm/{}"' \;

# ===== BIN ======

FROM ubuntu:24.04 
LABEL maintainer="Unique.Network"

COPY --from=builder /workdir/unique-chain/unique-collator /bin/unique-collator
COPY --from=builder /workdir/unique-chain/wasm /wasm
ENTRYPOINT ["/bin/unique-collator"]