# ===== Rust builder =====
FROM ubuntu:22.04 as rust-builder
LABEL maintainer="Unique.Network"

ENV CARGO_HOME="/cargo-home"
ENV PATH="/cargo-home/bin:$PATH"
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y curl cmake pkg-config libssl-dev git clang llvm libudev-dev protobuf-compiler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

RUN rustup toolchain install {{ RUST_TOOLCHAIN }} && \
    rustup target add wasm32-unknown-unknown --toolchain {{ RUST_TOOLCHAIN }} && \
    rustup default {{ RUST_TOOLCHAIN }} && \
    rustup component add --toolchain {{ RUST_TOOLCHAIN }} rust-src && \
    rustup target list --installed && \
    rustup show

RUN mkdir /unique_parachain
WORKDIR /unique_parachain

# ===== BUILD ACALA =====
FROM rust-builder as builder-acala-bin

WORKDIR /unique_parachain

RUN git clone -b {{ ACALA_BUILD_BRANCH }} --depth 1 https://github.com/AcalaNetwork/Acala.git

RUN --mount=type=cache,target=/cargo-home/registry \
    --mount=type=cache,target=/cargo-home/git \
    --mount=type=cache,target=/unique_parachain/Acala/target \
    cd Acala && \
    make init && \
    make build-release && \
    mv ./target/production/acala /unique_parachain/Acala/

# ===== BIN ======

FROM ubuntu:22.04 as builder-acala

COPY --from=builder-acala-bin /unique_parachain/Acala/acala /bin/acala
ENTRYPOINT ["/bin/acala"]
