// Template adopted from https://github.com/paritytech/substrate/blob/master/.maintain/frame-weight-template.hbs

//! Autogenerated weights for pallet_data_management
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-23, STEPS: `50`, REPEAT: 80, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// target/release/unique-collator
// benchmark
// pallet
// --pallet
// pallet-data-management
// --wasm-execution
// compiled
// --extrinsic
// *
// --template
// .maintain/frame-weight-template.hbs
// --steps=50
// --repeat=80
// --heap-pages=4096
// --output=./pallets/data-management/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_data_management.
pub trait WeightInfo {
	fn begin() -> Weight;
	fn set_data(b: u32, ) -> Weight;
	fn finish(b: u32, ) -> Weight;
	fn insert_eth_logs(b: u32, ) -> Weight;
	fn insert_events(b: u32, ) -> Weight;
}

/// Weights for pallet_data_management using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: DataManagement MigrationPending (r:1 w:1)
	// Storage: System Account (r:1 w:0)
	// Storage: EVM AccountCodes (r:1 w:0)
	fn begin() -> Weight {
		Weight::from_ref_time(16_080_000 as u64)
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: DataManagement MigrationPending (r:1 w:0)
	// Storage: EVM AccountStorages (r:0 w:1)
	fn set_data(b: u32, ) -> Weight {
		Weight::from_ref_time(7_945_000 as u64)
			// Standard Error: 1_272
			.saturating_add(Weight::from_ref_time(1_056_832 as u64).saturating_mul(b as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(b as u64)))
	}
	// Storage: DataManagement MigrationPending (r:1 w:1)
	// Storage: EVM AccountCodes (r:0 w:1)
	fn finish(b: u32, ) -> Weight {
		Weight::from_ref_time(8_336_000 as u64)
			// Standard Error: 89
			.saturating_add(Weight::from_ref_time(6_411 as u64).saturating_mul(b as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	fn insert_eth_logs(b: u32, ) -> Weight {
		Weight::from_ref_time(3_447_000 as u64)
			// Standard Error: 843
			.saturating_add(Weight::from_ref_time(901_039 as u64).saturating_mul(b as u64))
	}
	fn insert_events(b: u32, ) -> Weight {
		Weight::from_ref_time(3_457_000 as u64)
			// Standard Error: 1_460
			.saturating_add(Weight::from_ref_time(1_491_611 as u64).saturating_mul(b as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: DataManagement MigrationPending (r:1 w:1)
	// Storage: System Account (r:1 w:0)
	// Storage: EVM AccountCodes (r:1 w:0)
	fn begin() -> Weight {
		Weight::from_ref_time(16_080_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(3 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: DataManagement MigrationPending (r:1 w:0)
	// Storage: EVM AccountStorages (r:0 w:1)
	fn set_data(b: u32, ) -> Weight {
		Weight::from_ref_time(7_945_000 as u64)
			// Standard Error: 1_272
			.saturating_add(Weight::from_ref_time(1_056_832 as u64).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(b as u64)))
	}
	// Storage: DataManagement MigrationPending (r:1 w:1)
	// Storage: EVM AccountCodes (r:0 w:1)
	fn finish(b: u32, ) -> Weight {
		Weight::from_ref_time(8_336_000 as u64)
			// Standard Error: 89
			.saturating_add(Weight::from_ref_time(6_411 as u64).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
	}
	fn insert_eth_logs(b: u32, ) -> Weight {
		Weight::from_ref_time(3_447_000 as u64)
			// Standard Error: 843
			.saturating_add(Weight::from_ref_time(901_039 as u64).saturating_mul(b as u64))
	}
	fn insert_events(b: u32, ) -> Weight {
		Weight::from_ref_time(3_457_000 as u64)
			// Standard Error: 1_460
			.saturating_add(Weight::from_ref_time(1_491_611 as u64).saturating_mul(b as u64))
	}
}
